### ISSUE TITLE
Undefined babelPlugins?

### ISSUE THREAD

**Issue by baebb** [serverless/serverless-babel-plugin#19]
When trying to compile with babel I get this error:
```
Users/rdyson/dev/smsLambda/node_modules/serverless-babel-plugin/index.js:63
          --plugins=${this.serverless.service.custom.babelPlugins.join(',')},
                                                                  ^

TypeError: Cannot read property 'join' of undefined
    at Extract.stream.on (/Users/rdyson/dev/smsLambda/node_modules/serverless-babel-plugin/index.js:63:67)
    at emitNone (events.js:91:20)
    at Extract.emit (events.js:185:7)
    at DirWriter.<anonymous> (/Users/rdyson/dev/smsLambda/node_modules/unzip2/lib/extract.js:42:10)
    at emitNone (events.js:91:20)
    at DirWriter.emit (events.js:185:7)
    at end (/Users/rdyson/dev/smsLambda/node_modules/fstream/lib/writer.js:323:12)
    at /Users/rdyson/dev/smsLambda/node_modules/fstream/lib/writer.js:313:32
    at endUtimes (/Users/rdyson/dev/smsLambda/node_modules/fstream/lib/writer.js:239:48)
    at setProps (/Users/rdyson/dev/smsLambda/node_modules/fstream/lib/writer.js:296:5)
    at /Users/rdyson/dev/smsLambda/node_modules/fstream/lib/writer.js:286:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```

My serverless.yml:
```
service: sms-lambda

custom:
  babelPresets:
    - stage-1

plugins:
  - serverless-babel-plugin

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          path: send
          method: post
```

My package.json:
```
{
  "name": "sms-lambda",
  "version": "0.1.0",
  "main": "handler.js",
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "serverless-babel-plugin": "^0.2.0"
  },
  "dependencies": {
    "axios": "^0.16.1",
    "query-string": "^4.3.4"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Ross Dyson",
  "license": "MIT"
}
```
