### ISSUE TITLE
Not working when a function handler is in a subdirectory

### ISSUE THREAD

**Issue by plbrault** [serverless/serverless-babel-plugin#3]
I have a Lambda function which the handler is in a subdirectory, e.g.:

```
functions:
  myFunction:
    handler: myFunction/handler.myFunction
```

When I deploy with the plugin enabled, the handler is not included in the generated archive, thus my deployed function does not work.

I am using this plugin with Serverless 1.2.0.

**Comment by nikgraf** [comment]
@plbrault thx for reporting. That's indeed a bug. I hope I get to fix it tomorrow or Monday.

**Comment by evfleet** [comment]
Curious if there has been any progress towards this bug. This package would be amazing for my use case if you can use handlers within subdirectories.

Thanks for your work!

**Comment by plbrault** [comment]
Has there been any progress on this?

**Comment by nikgraf** [comment]
I'm not working actively on it. Would you be interested taking ownership in this project?

**Comment by peisenhower** [comment]
@nikgraf Do you know where i could start looking to fix this bug.

**Comment by samwiseduzer** [comment]
@nikgraf @peisenhower any progress on this?

**Comment by mattishaden** [comment]
Any workarounds for this for the moment?

**Comment by brandon-arnold** [comment]
Still doesn't work in 2018.

**Comment by johneast** [comment]
I have this issue.
My functions are written in typescript and compiled to a folder called 'out'. They are then packaged up as so:

```
functions:
  myfunction:
    handler: out/myfunction.handler
    package:
      include:
        - out/myfunction.js
```

After running `serverless package` I can see the generated zip file contains the correct folder and file. After running `serverless deploy`, the lambda function created in AWS is empty.

I should also say, this has nothing to do with the babel plugin as I'm not using that.

**Comment by hraban** [comment]
I was running into a similar problem, what helped me get around it was building my own .zip artifact with everything in the root and specifying that in the serverless.yml using the package.artifact key.

@johneast your serverless.yml looks odd, btw; package is a top-level directive, not a sub node of functions.&lt;funcname&gt;:

```yml
functions:
  myfunction:
    handler: out/myfunction.handler
package:
  include:
    - out/myfunction.js
```

Anyway, package.include didn't work for me (it would include the entire dir), so I ended up going with package.artifact, instead.

**Comment by Chanonry** [comment]
Multi function independently packaged approach does not seem to work at all. 

Handler function not present; unzip_requirement.py hidden in a complex directory structure; other irrelevant directories included in the zip. 

Generally not up to it for a real use case. Shame

**Comment by mxkrn** [comment]
Would also be interested in seeing this exist

**Comment by Chanonry** [comment]
Yes !

**Comment by jundialwan** [comment]
This is interesting feature. I think this is might be useful for me who use Typescript, cases like @johneast. Yes, `serverless-plugin-typescript` is exist for Typescript project but that would be great if this alternative method to refer subfolder handler exist.

**Comment by mtsz-thiago** [comment]
I'm still facing the same issue. It seams that it  is considered a very low priority bug

**Comment by jdk514** [comment]
I've been able to resolve this problem by placing a './' in front of the directory name.

Example Project Structure:
- Project_Dir
  - lambda_functions
    - sample_lambda
      - app.py
  - template.yaml

Example Yaml:
```YAML
Resources:

    SampleLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./lambda_functions/sample_lambda/
            Handler: app.lambda_handler
            Runtime: python3.8
```
